spring.application.name=springbootRegLogin-3
spring.datasource.url=jdbc:mysql://localhost:3306/ pankaj
spring.datasource.username=root
spring.datasource.password=Pankaj97

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8081
